### ISSUE TITLE
DataHub Button Disappears

### ISSUE THREAD

**Issue by CountZero1981** [CI-HUB-GmbH/PimcoreCIHubAdapterBundle#1]
When I enable the bundle in bundles.php, DataHub button disappears. If I enable the bundle in Pimcore dashboard, DataHub button also disappears sometimes.

**Comment by aarongerig** [comment]
The `bundles.php` file is used to register regular Symfony bundles. In this case though, we are dealing with a Pimcore bundle, which needs to be enabled either through the Pimcore Extension Manager or via CLI commands.

Do you get some error messages when doing so, @CountZero1981 ?

**Comment by aarongerig** [comment]
@CountZero1981 Feel free to comment once you have another question or remark. Meanwhile I'm closing the issue.
