### ISSUE TITLE
Error when saving CI Hub data hub configuration without dao classes / object workspace

### ISSUE THREAD

**Issue by birgerstoeckelmann** [CI-HUB-GmbH/PimcoreCIHubAdapterBundle#2]
We would like to use the CI-Hub integration only for assets. After saving the configuration an error is displayed, details in the screenshot below. Saving the configuration again is successfull.

Unfortunately existing assets are not indexed in Elastic Search (for the given workspaces), only assets uploaded after saving the configuration, and therefor not available via /pimcore-datahub-webservices/simplerest/CONFIG_KEY/tree-items API.

Steps to reproduce:

- create a configuration without data object classes
- add an asset workspace only
- add/generate api key
- save configuration

![Bildschirmfoto 2022-08-16 um 19 38 18](https://user-images.githubusercontent.com/10415259/184944902-7961de46-2a88-45dc-a226-15e0b68be29f.png)

Pimcore: 10.5.2
ci-hub/simple-rest-adapter-bundle: 2.0.2
ci-hub/pimcore-ci-hub-adapter-bundle: 2.0.1
symfony/doctrine-messenger: 5.4.11
elasticsearch: 7.17.1

**Comment by aarongerig** [comment]
@birgerstoeckelmann Thanks for reporting! That should definitely be possible. I'll have a look and you'll hear from me...

**Comment by aarongerig** [comment]
Resolved by https://github.com/CI-HUB-GmbH/SimpleRESTAdapterBundle/commit/1259291c918380e497b74b80064b635b7768ebc9

@birgerstoeckelmann Could you also please test that on your project? I'll release a new version shortly.

Edit: https://github.com/CI-HUB-GmbH/SimpleRESTAdapterBundle/releases/tag/v2.0.3

**Comment by birgerstoeckelmann** [comment]
@aarongerig Both bundles work very well now. The DataHub configuration is saved without errors and existing assets are indexed immediately. Deleting items in the Pimcore backend works as expected.
Thanks again for your quick support and fixing these errors!
