### ISSUE TITLE
Pimcore 11 compatiblity

### ISSUE THREAD

**Issue by betterapp** [CI-HUB-GmbH/PimcoreCIHubAdapterBundle#5]
When are You planning update those package to Pimcore 11 ?

**Comment by micru** [comment]
Any news on this? We need compatibility with pimcore 11 for a customer of ours who would like to use CI Hub

**Comment by betterapp** [comment]
https://ci-hub.com/integration/pimcore

Requirements
We are offering the CI HUB Connector for Pimcore Versions.
Requirements: the provided data connector and Pimcore Version 11. All Pimcore partners who sign a [CI HUB reseller agreement](https://ci-hub.com/sales-club-registration) will receive our support.

The New Integration requires two Pimcore Connector Bundles; these are available directly on GitHub. Please follow the links:

https://github.com/BrandOriented/PimcoreCIHubAdapterBundle

https://github.com/BrandOriented/PimcoreCiHubConnector
